<?php
/**
 * @file
 * Code for Farm Map: Norway.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function farm_map_no_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "openlayers" && $api == "default_openlayers_layers") {
    return array("version" => "1");
  }
  if ($module == "openlayers" && $api == "default_openlayers_sources") {
    return array("version" => "1");
  }
}

/**
 * Define the URL of the Kartverket WMTS.
 */
function farm_map_no_kartverket_wmts() {
  return 'http://opencache.statkart.no/gatekeeper/gk/gk.open_wmts';
}

/**
 * List the layers to include from Kartverket's WMTS.
 */
function farm_map_no_kartverket_wmts_layers() {
  return array(
    'norges_grunnkart' => t('Norges Grunnkart'),
    'topo2' => t('Topo2'),
  );
}

